# Generated by Django 4.2.4 on 2023-08-15 20:54

from django.db import migrations, models
import phonenumber_field.formfields


class Migration(migrations.Migration):

    dependencies = [
        ('Lorenzo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeusDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('habilitacao', models.CharField(max_length=10)),
                ('formacao', models.TextField(max_length=10000)),
                ('experiencias', models.TextField(max_length=10000)),
                ('cursos', models.TextField(max_length=10000)),
                ('infos_complementares', models.TextField(max_length=10000)),
            ],
            bases=(models.Model, phonenumber_field.formfields.PhoneNumberField),
        ),
    ]
