# Generated by Django 4.2.4 on 2023-08-15 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Lorenzo', '0003_meusdados_celular_whatsapp_alter_meusdados_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeuPortifolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projeto', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=10000)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('download', models.FileField(upload_to='')),
            ],
        ),
    ]
