# Generated by Django 4.2.4 on 2023-08-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lorenzo', '0004_meuportifolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='meuportifolio',
            name='imagem',
            field=models.ImageField(default=None, upload_to='imagens'),
        ),
        migrations.AlterField(
            model_name='meuportifolio',
            name='download',
            field=models.FileField(upload_to='projetos'),
        ),
    ]
