# Generated by Django 4.2.4 on 2023-08-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lorenzo', '0005_meuportifolio_imagem_alter_meuportifolio_download'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuportifolio',
            name='imagem',
            field=models.ImageField(upload_to='imagens'),
        ),
        migrations.AlterField(
            model_name='meusdados',
            name='celular_whatsapp',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='meusdados',
            name='habilitacao',
            field=models.CharField(max_length=20),
        ),
    ]
