# Generated by Django 4.2.4 on 2023-08-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lorenzo', '0006_alter_meuportifolio_imagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
