# Generated by Django 4.2.4 on 2023-08-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lorenzo', '0007_contato'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
