# Generated by Django 4.2.4 on 2023-08-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lorenzo', '0008_delete_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='meusdados',
            name='endereco',
            field=models.CharField(default='', max_length=30),
        ),
    ]
