# Generated by Django 4.2.4 on 2023-08-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lorenzo', '0009_meusdados_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meusdados',
            name='endereco',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
