# Generated by Django 4.2.4 on 2023-08-17 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lorenzo', '0010_alter_meusdados_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meusdados',
            name='cursos',
        ),
        migrations.RemoveField(
            model_name='meusdados',
            name='experiencias',
        ),
        migrations.RemoveField(
            model_name='meusdados',
            name='formacao',
        ),
        migrations.RemoveField(
            model_name='meusdados',
            name='infos_complementares',
        ),
        migrations.CreateModel(
            name='Infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infor', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=10000)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='Lorenzo.meusdados')),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formacao', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=10000)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formacao', to='Lorenzo.meusdados')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=10000)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencia', to='Lorenzo.meusdados')),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=50)),
                ('descricao', models.TextField(max_length=10000)),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='Lorenzo.meusdados')),
            ],
        ),
    ]
