# Generated by Django 4.2.4 on 2023-08-17 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lorenzo', '0011_remove_meusdados_cursos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='descricao',
            new_name='descricao_curso',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='nome',
            new_name='nome_curso',
        ),
        migrations.RenameField(
            model_name='experiencias',
            old_name='descricao',
            new_name='descricao_exp',
        ),
        migrations.RenameField(
            model_name='experiencias',
            old_name='nome',
            new_name='nome_experiencia',
        ),
        migrations.RenameField(
            model_name='formacao',
            old_name='descricao',
            new_name='descricao_formacao',
        ),
        migrations.RenameField(
            model_name='formacao',
            old_name='nome',
            new_name='nome_formacao',
        ),
        migrations.RenameField(
            model_name='infos',
            old_name='descricao',
            new_name='descricao_info',
        ),
        migrations.RenameField(
            model_name='infos',
            old_name='infor',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='infos',
            old_name='nome',
            new_name='nome_info',
        ),
        migrations.RenameField(
            model_name='meuportifolio',
            old_name='descricao',
            new_name='descricao_projeto',
        ),
    ]
