# Generated by Django 4.2.4 on 2023-08-17 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lorenzo', '0013_rename_descricao_curso_cursos_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='minhahistoria',
            name='nome',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='minhahistoria', to='Lorenzo.meusdados'),
            preserve_default=False,
        ),
    ]
