# Generated by Django 4.2.4 on 2023-08-21 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lorenzo', '0014_minhahistoria_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minhahistoria',
            name='imagem',
        ),
    ]
