# Generated by Django 4.2.4 on 2023-08-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lorenzo', '0015_remove_minhahistoria_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuportifolio',
            name='download',
            field=models.FileField(upload_to='media/projetos'),
        ),
        migrations.AlterField(
            model_name='meuportifolio',
            name='imagem',
            field=models.ImageField(upload_to='media/imagens'),
        ),
    ]
