# Generated by Django 4.2.4 on 2023-08-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lorenzo', '0016_alter_meuportifolio_download_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infos',
            name='nivel',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4),
        ),
    ]
