# Generated by Django 4.2.4 on 2023-08-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lorenzo', '0018_remove_meuportifolio_download_meuportifolio_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meuportifolio',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
